# Generated by Django 5.1.4 on 2025-01-09 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('avalanche', 'Avalancha'), ('snowball', 'Bola de nieve')], max_length=20)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='debts.debt')),
            ],
        ),
    ]
